services:
  php:
    build: .
    container_name: php
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./www:/app/www
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/frankenphp/Caddyfile
      - ./caddy/sites:/etc/frankenphp/sites
      # - ./php/php.ini:/usr/local/etc/php/php.ini
      # - ./php/conf.d:/usr/local/etc/php/conf.d
    environment:
      WP_DB_HOST: mariadb
      WP_DB_NAME: database
      WP_DB_USER: root
      WP_DB_PASSWORD: root
    depends_on:
      - mariadb

    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mariadb/files:/src
      - mariadb_data:/var/lib/mysql
      - mariadb_config:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_data:/data

volumes:
  caddy_data:
  caddy_config:
  mariadb_data:
  mariadb_config:
  redis_data:
